import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'StellarTickets — Tickets You Can Actually Verify',
    short_name: 'StellarTickets',
    description:
      'Issue, manage, verify, transfer, and resell blockchain-powered tickets on the Stellar network.',
    start_url: '/',
    display: 'standalone',
    background_color: '#000000',
    theme_color: '#8b5cf6',
    icons: [
      {
        // Generated by app/icon.tsx — same LogoMark used everywhere else (#123).
        src: '/icon',
        sizes: '32x32',
        type: 'image/png',
      },
    ],
  };
}
